### ISSUE TITLE
Declaration always includes triple slash reference in build output

### ISSUE THREAD

**Issue by arthurfiorette** [nonara/ts-expose-internals#14]
See https://github.com/vega/ts-json-schema-generator/issues/1967.

We're using `ts-expose-internals` to type check some internal methods and properties.

However, as the project can be used as a library we cannot force everyone up in the dependency tree to also have all `typescript` internals available. This package should only be loaded in our development and never referenced in the final build output.

However, [as you can see](https://www.npmjs.com/package/ts-json-schema-generator/v/2.2.0?activeTab=code), every `d.ts` file that has a import to `typescript`, the `tsc` automatically adds a triple slash reference for this package, which should not happen.

I understand that it does this by default because we could do a `export function test(): ts.SomethingThatOnlyIsDeclaredInTsExposeInternals` and ts would need to either import `ts-expose-internals` or emit a invalid declaration, but this is not the case here and every time I load this package, either by dependency alias to `@types/*` or something else, every dts file gets modified.

Is there a way to solve this?

**Comment by nonara** [comment]
Hey @arthurfiorette!

That's an interesting situation. It does make sense, as I see you're doing `import ts from "typescript"`, which would include everything we've augmented.

You might be able to have separate tsconfig files to specify exclusion of that. Perhaps a direct (non `@type` scope aliased) dev-dependency and have a tsconfig file for your primary build, in which you explicitly exclude that file.

Another option would be post-processing of files with simple regex to find and remove the whole triple-slash line.

Finally, you could always use [byots](https://www.npmjs.com/package/byots), which doesn't use module augmentation technique for when you're doing internal things that won't be built into the declarations files.

If you try the first method, please let me know if it works!

I think an ultimately solution on our wns, which could help, is to output the untransformed secondary `typescript.d.ts` file to the package alongside the module augmentation version, so people in your situation could directly import that.

I don't have the time atm, but PRs are welcome.

**Comment by nonara** [comment]
Hey @andrewbranch! I just stumbled across [ts-expose-internals-conditionally](https://github.com/andrewbranch/ts-expose-internals-conditionally). Looks like this is the same issue! 

I'm thinking over what may be a better approach here. One thing that comes to mind that would probably be the most ideal is to identify what is tagged internal and elide everything that isn't referenced by them, or those that are referenced but are accessible from the live module. 

I think the trick here would be that we don't have `@internal` tags on the built declarations file. If there's a way to preserve those during build, that would be great.

Otherwise, we could probably build two outputs — one with and one without internals. Then we can walk the two and potentially just compare the source strings of each statement. Anything with no differences gets skipped, and for those that differ, we can drill into children recursively to perform the same check. When we hit a non-module declaration that's fundamentally different, we'd flag it.

Then we can derive dependents from there and create our final output.

In that way, we'd end up with an output file which only contains the internals that augment on top of the original. I imagine that would also be a nice speed boost. 

Overall, that would likely be more in line with what users should expect when using this. If anyone complains about the triple-slash then, we can simply direct them to avoid exporting internal types or include the library as a full dependency.

These are just first thoughts, so hopefully I'm not missing any obvious reason this wouldn't work, etc., but I thought I'd get them down really quick. What do you think?

**Comment by andrewbranch** [comment]
Thanks for the ping—this is indeed why I made ts-expose-internals-conditionally.

> tsc automatically adds a triple slash reference for this package, which should not happen

This (longstanding) behavior has been removed in TypeScript 5.5: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-rc/#simplified-reference-directive-declaration-emit. So I think this is a non-issue going forward, and I can deprecate ts-expose-internals-conditionally as well. @arthurfiorette do you want to try out `typescript@5.5.1-rc` and make sure it solves your issue?
