### ISSUE TITLE
tsconfig.json "types" field

### ISSUE THREAD

**Issue by osyrisrblx** [nonara/ts-expose-internals#7]
I noticed if I add `"types": ["ts-expose-internals"],` to my `tsconfig.json` file, I can get the `ts-expose-internals` typings without the need for an import statement.

Seems like there could be drawbacks if you have `@types/*` packages which inject globals. I think you'd need to specify those as well in `"types"`, but I don't think that's a big deal.

https://www.typescriptlang.org/tsconfig#types

Maybe this should be added to the documentation as an alternative usage method?

**Comment by nonara** [comment]
That does work, yes! 

I considered mentioning that in the directions. Unfortunately, though, as you mentioned, specifying a `types` field makes it so that the normal behaviour of automatically adding `@types` packages no longer works. For that reason, most projects do not use that field. I also imagine that many users are unfamiliar with how that setting works. I remember being a surprised at the behaviour when I first tried using the types field in one of my projects.

Ultimately, I decided that adding it to the readme would end up with a lot of tickets coming in, but I figured that those who knew the setting would probably be able to figure it out if they wanted to use it 😅  

I agree with you, though, I do wish there was an easier way to just specify via tsconfig!

Another route is `import type tsei from 'typescript-expose-internals'`, which avoids the empty brackets. Only works on semi-recent versions of TS, though.
